import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');

/**
 * Authenticating to the Authority Service from the acceptance suite.
 *
 * The shell counterpart of this is scripts/lib/authority-auth.sh, and it exists for the
 * same reason: the administrative API is reached one way on a development stack and
 * another way on a deployment, and a test that hard-codes either is a test that only
 * proves one of them.
 *
 *   ENABLE_AUTH=false   x-dev-issuer / x-dev-subject name the caller directly
 *   ENABLE_AUTH=true    an OAuth2 client-credentials token from the `authority` realm
 *
 * Which is in force is DISCOVERED from the service. A suite told the wrong mode would
 * authenticate as nobody and report authorisation failures as functional ones.
 */

let mode = null;
const tokens = new Map(); // principal -> { token, expiresAt }

function envFile() {
  try {
    return readFileSync(join(ROOT, 'deploy', '.env'), 'utf8');
  } catch {
    return '';
  }
}

function envval(key) {
  if (process.env[key]) return process.env[key];
  const match = new RegExp(`^${key}=(.*)$`, 'm').exec(envFile());
  return match ? match[1] : '';
}

/** Dev-mode subject names, matching the shell helper's defaults. */
const DEV_SUBJECT = {
  BOOTSTRAP: 'bootstrap',
  FARMER_OPERATOR: 'agri-farmer-operator',
  LAND_OPERATOR: 'agri-land-operator',
  FARMER_OFFICER: 'agri-farmer-officer',
  LAND_OFFICER: 'agri-land-officer',
};

export async function authorityMode(authorityBase) {
  if (mode) return mode;
  let status = 0;
  try {
    const response = await fetch(`${authorityBase}/api/v1/tenants`);
    status = response.status;
  } catch {
    status = 0;
  }
  mode = status === 401 ? 'token' : 'dev';
  return mode;
}

async function token(principal, opsBase) {
  const cached = tokens.get(principal);
  if (cached && Date.now() < cached.expiresAt) return cached.token;

  const clientId = envval(`AUTHORITY_CLIENT_${principal}`);
  const clientSecret = envval(`AUTHORITY_SECRET_${principal}`);
  if (!clientId || !clientSecret) {
    throw new Error(
      `no client credentials for ${principal}. Run scripts/bootstrap-authority-realm.sh, ` +
        'which writes them to deploy/.env.',
    );
  }

  // Through the operator listener, exactly as the shell helper does: the realm pins its
  // own issuer, so a token fetched here is identical to one the issuing services obtain
  // over the container network.
  const url = `${opsBase}/auth/realms/${process.env.AUTHORITY_REALM || 'authority'}/protocol/openid-connect/token`;
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'content-type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      grant_type: 'client_credentials',
      client_id: clientId,
      client_secret: clientSecret,
    }),
  });
  if (!response.ok) {
    throw new Error(`token endpoint answered ${response.status} for ${clientId}`);
  }
  const body = await response.json();
  const lifetime = Number(body.expires_in) > 0 ? Number(body.expires_in) : 60;
  tokens.set(principal, {
    token: body.access_token,
    expiresAt: Date.now() + Math.max(lifetime - 10, 5) * 1000,
  });
  return body.access_token;
}

/**
 * Headers that authenticate as `principal`, whichever mode the deployment is in.
 *
 * `principal` is one of BOOTSTRAP, FARMER_OPERATOR, LAND_OPERATOR, FARMER_OFFICER,
 * LAND_OFFICER — a role, not a subject string, because with authentication on the
 * subject is a service account id generated by Keycloak.
 */
export async function authorityHeaders(principal, { authorityBase, opsBase }) {
  const common = { 'content-type': 'application/json' };
  if ((await authorityMode(authorityBase)) === 'dev') {
    const subject = DEV_SUBJECT[principal];
    if (!subject) throw new Error(`unknown principal ${principal}`);
    return { ...common, 'x-dev-issuer': 'https://idp.test', 'x-dev-subject': subject };
  }
  return { ...common, authorization: `Bearer ${await token(principal, opsBase)}` };
}
