const flow = (nodes) => '<div class="flow doc-flow">' + nodes.map((n,i) => '<div class="flow-node '+(i===1?'primary-node':'')+'"><span class="node-number">0'+(i+1)+'</span><strong>'+n[0]+'</strong><small>'+n[1]+'</small></div>' + (i<nodes.length-1?'<span class="flow-arrow">→</span>':'')).join('') + '</div>';
const video = (text,status='Public showcase video · coming soon') => '<section class="video-panel compact"><div class="video-art"><span>▶</span></div><div><p class="section-kicker">WATCH THE APPLICATION</p><h2>See the complete journey</h2><p>'+text+'</p><span class="coming-soon">'+status+'</span></div></section>';
const actors = rows => '<div class="table-wrap"><table><thead><tr><th>Actor</th><th>Responsibility</th><th>Illustrative global examples</th></tr></thead><tbody>'+rows.map(r=>'<tr><td><strong>'+r[0]+'</strong></td><td>'+r[1]+'</td><td>'+r[2]+'</td></tr>').join('')+'</tbody></table></div>';
const ecosystemScope = rows => '<div class="scope-legend"><span class="demonstrated">Demonstrated</span><span class="simulated">Represented with synthetic data/configuration</span><span class="boundary">Production integration boundary</span><span class="outside">Not addressed by this reference application</span></div><div class="table-wrap ecosystem-table"><table><thead><tr><th>Ecosystem participant</th><th>Role in the ecosystem</th><th>What this reference implementation covers</th><th>What a real implementation must supply</th></tr></thead><tbody>'+rows.map(r=>'<tr><td><strong>'+r[0]+'</strong></td><td>'+r[1]+'</td><td><span class="scope-tag '+r[2]+'">'+r[3]+'</span><br>'+r[4]+'</td><td>'+r[5]+'</td></tr>').join('')+'</tbody></table></div>';
const steps = items => '<ol class="steps">'+items.map((x,i)=>'<li><span>'+String(i+1).padStart(2,'0')+'</span><p>'+x+'</p></li>').join('')+'</ol>';
const baseHeader=(kicker,title,lead,status='')=>'<p class="breadcrumb">Applications · '+kicker+'</p><header class="doc-hero">'+(status?'<span class="status">'+status+'</span>':'')+'<h1>'+title+'</h1><p class="lead">'+lead+'</p></header>';
const lifecycle=(credentials,presentation,verification)=>'<section class="credential-lifecycle"><p class="section-kicker">CREDENTIAL LIFECYCLE</p><h2>What is issued, stored, presented and verified</h2><p class="synthetic-warning"><strong>Synthetic demonstration data.</strong> The names, identifiers, records and values below are fictional examples for explaining the reference application. They are not real people, official records or production credential schemas.</p><div class="lifecycle-flow"><span>ISSUE</span><i>→</i><span>STORE IN WALLET</span><i>→</i><span>PRESENT WITH CONSENT</span><i>→</i><span>VERIFY & DECIDE</span></div><div class="credential-grid">'+credentials.map(c=>'<article><p class="credential-type">'+c[0]+'</p><h3>'+c[1]+'</h3><pre>'+c[2]+'</pre><p>'+c[3]+'</p></article>').join('')+'</div><div class="presentation-grid"><div><p class="section-kicker">PRESENTED</p><h3>Minimum information shared</h3><pre>'+presentation+'</pre></div><div><p class="section-kicker">VERIFIED</p><h3>Checks before the service decision</h3><ul>'+verification.map(x=>'<li>'+x+'</li>').join('')+'</ul></div></div></section>';

const docs = {
age: baseHeader('Identity and access','Privacy-preserving age verification','Prove an age condition without sharing a complete identity record or exact date of birth.')+
'<section id="problem"><p class="section-kicker">THE REAL-WORLD NEED</p><h2>The problem</h2><p>Age checks are required for regulated goods, age-restricted content and venues, age-bound programmes, benefits and public services. In most cases the service needs a simple answer—whether a person satisfies an age threshold—not the person’s complete identity.</p><p>The common approach asks people to upload, photocopy or display an identity document. That exposes a full name, exact date of birth, address, photograph and identity number, and may leave the verifier holding a sensitive copy. Digital services must also inspect documents, calculate age, detect tampering and determine whether the issuer is trusted.</p><p>The need is a reusable digital proof that answers the specific age question, originates from an authoritative source, stays under the citizen’s control and avoids unnecessary identity disclosure.</p></section>'+
'<section id="actors" class="ecosystem-scope"><p class="section-kicker">ECOSYSTEM</p><h2>Participants, reference coverage and integration boundaries</h2><p>This combined view shows who participates, the responsibility each role carries, what the reference application demonstrates or represents, and where a production ecosystem must complete the integration.</p>'+ecosystemScope([['Citizen or resident','Authenticates, receives and controls an age proof; for example, a resident using a national eID or civil identity.','demonstrated','Demonstrated','A synthetic citizen completes issuance and both presentation channels.','Real enrolment, recovery, accessibility, support and legal consent arrangements.'],['Identity provider','Authenticates the citizen and binds the session to the source record; for example, Singpass, an eIDAS-notified scheme or Aadhaar where lawful.','simulated','Represented','Keycloak authenticates synthetic National ID accounts.','Connection to the jurisdiction’s approved identity provider, assurance level and account lifecycle.'],['Identity authority and registry','Maintains authoritative identity and birth records; for example, a civil registry or national identity authority.','simulated','Represented','Sunbird RC holds synthetic citizen records and resolves the authenticated user.','Authoritative data onboarding, correction, stewardship, retention and lawful-use controls.'],['Credential issuer','Derives and signs the age condition under the authority’s mandate.','demonstrated','Demonstrated','The issuer creates a holder-bound SD-JWT credential directly for the wallet.','Issuer accreditation, production keys, revocation/expiry policy and audit operations.'],['Wallet provider','Protects the credential, displays the request and mediates holder consent.','demonstrated','Demonstrated','A customized standards-compatible open-source wallet stores and presents the credential.','Wallet selection, certification, device security, recovery and interoperability acceptance.'],['Age-restricted service','Requests minimum age evidence and decides access; for example, a retailer, platform, venue or public service.','demonstrated','Demonstrated','Web QR and mobile deep-link verifiers return approved or denied outcomes.','Integration into the real service, local age policy, exception handling and retention rules.'],['Trust and regulatory bodies','Define recognized issuers, permitted purposes and accountability.','outside','Not addressed','A configured allowlist stands in for ecosystem trust governance.','Legislation, accreditation, trust-list operation, dispute resolution and oversight.']])+'</section>'+
'<section id="solution"><p class="section-kicker">THE APPLICATION</p><h2>How the solution works</h2><p>The identity authority derives an age condition such as “over 18” from its authoritative record and issues an Age Verification Credential directly to the citizen’s wallet. The wallet stores reusable evidence and gives the citizen control over who receives it.</p><p>A service requests only the required age condition. After consent, the wallet creates a selective presentation. The service verifies the issuer, credential, holder and transaction before applying its access rule. The authority remains the source of truth, while the service never needs the exact date of birth.</p>'+flow([['Registry','Authoritative citizen record'],['Credential','Derived age condition'],['Wallet','Consent and selective proof'],['Service','Verify and decide']])+'</section>'+
lifecycle([['ISSUED BY IDENTITY AUTHORITY','Age Verification Credential','{\n  "credentialId": "AGE-VC-10027",\n  "ageOver18": true,\n  "issuedAt": "2026-08-20"\n}','Stored as a holder-bound SD-JWT credential in the citizen’s wallet. Exact date of birth and National ID remain undisclosed.']],'{\n  "ageOver18": true\n}', ['Trusted Identity Authority issued the credential.','Signature and approved algorithm are valid.','The presentation is controlled by the expected wallet holder.','The request is valid and bound to the current transaction.','The service applies its age-access rule.'])+
video('Direct wallet issuance, web QR verification, mobile deep-link verification, consent, minimum disclosure and approved and denied results.')+
'<section id="experience"><p class="section-kicker">EXPERIENCE</p><h2>Journey demonstrated</h2><h3>Obtain the credential</h3>'+steps(['Open the wallet and select the identity authority.','Authenticate through the identity provider.','Resolve the correct authoritative citizen record.','Issue directly to the wallet without an issuance QR.','Review and store the credential.'])+'<h3>Verify across devices or on the same device</h3>'+steps(['A website shows a QR code, or a mobile service invokes the wallet using a deep link.','The wallet displays the verifier and requested information.','The citizen consents to disclose the age condition.','The service verifies the presentation and displays APPROVED or DENIED.'])+'</section>'+
'<section class="information"><h2>Information design</h2><div class="compare"><div><span>Used by the issuer</span><strong>Authenticated identity and citizen record</strong></div><div><span>Shared with the verifier</span><strong>Required age condition</strong></div><div><span>Kept private</span><strong>Date of birth, address and unrelated identity details</strong></div></div></section>'+
'<section id="adapt"><p class="section-kicker">REPLICATE THE PATTERN</p><h2>How to adapt it</h2>'+steps(['Identify the authority able to determine the required age condition.','Model or connect authoritative records.','Define a purpose-specific credential without unnecessary identity claims.','Configure authentication-to-record mapping and issuer trust.','Compatibility-test the chosen wallet and protocol profile.','Request only the required assertion.','Add local policy, privacy, retention, revocation and operational controls.'])+'</section>',

agriculture: baseHeader('Agriculture and finance','Farmer and land credentials for rural credit','Bring trusted evidence from independent Farmer and Land registries into a lender’s digital journey.')+
'<section id="problem"><p class="section-kicker">THE REAL-WORLD NEED</p><h2>The problem</h2><p>Farmers need seasonal and working-capital finance for seed, fertilizer, equipment and other inputs. Lenders may need to establish farmer registration, land ownership or tenure, crop type and cultivated acreage before making a credit decision.</p><p>Those facts usually come from different authorities with different identifiers and records. Farmers collect documents from multiple offices; lenders inspect them, reconcile identities and manually enter data. This creates delays, excess disclosure and opportunities for altered or mismatched records.</p><p>Point-to-point connections between every lender and every registry create another form of complexity. The ecosystem needs portable, consented evidence from independent authoritative sources.</p></section>'+
'<section id="actors" class="ecosystem-scope"><p class="section-kicker">ECOSYSTEM</p><h2>Participants, reference coverage and integration boundaries</h2><p>The reference application connects farmer and land evidence to a sample lending decision. This combined view separates the demonstrated credential journey from the broader agricultural-finance responsibilities.</p>'+ecosystemScope([['Farmer','Authenticates, obtains two credentials and consents to presentation; representing a smallholder, tenant, cooperative member or commercial farmer.','demonstrated','Demonstrated','Multiple synthetic farmers complete the wallet journey.','Real enrolment, assisted access, corrections, recovery and grievance support.'],['Identity provider','Authenticates National ID and connects the person to farmer and land records.','simulated','Represented','Keycloak maps synthetic National IDs deterministically.','Approved national or sector identity integration, assurance and account lifecycle.'],['Farmer Registry and agriculture authority','Maintain farmer identity, registration, status and programme information; typically a ministry, agency or cooperative registry.','simulated','Represented','A separate Sunbird RC entity supplies the Farmer credential.','Authoritative onboarding, stewardship, crop-data sources, correction and update processes.'],['Land Registry','Maintains land identity, ownership, acreage and crop information; typically a cadastral, deeds or titles authority.','simulated','Represented','A separate entity and issuer supply one synthetic ownership record per farmer.','Cadastral/title integration, tenure complexity, disputes, leases, encumbrances and change events.'],['Credential issuers','Issue independently trusted Farmer and Land credentials.','demonstrated','Demonstrated','Separate issuer identities and role-specific trust are verified.','Issuer onboarding, production keys, revocation/expiry and trust-registry operation.'],['Wallet provider','Stores both credentials and presents selected claims together.','demonstrated','Demonstrated','The customized open-source wallet preserves issuer separation and holder consent.','Production wallet assurance, recovery, device security and interoperability testing.'],['Bank or lender','Verifies evidence, correlates the farmer and applies credit policy; for example, a rural bank, cooperative or microfinance provider.','demonstrated','Demonstrated','A mock bank calculates a maximum using verified crop and acreage claims.','KYC/AML, credit risk, pricing, underwriting, sanction, disbursement, repayment and servicing.'],['Agricultural and financial governance','Define recognized authorities, crop rates and regulated lending rules.','outside','Not addressed','Static configuration represents trust and crop-rate policy.','Regulatory approval, governed rates, audit, appeals, liability and ecosystem operations.']])+'</section>'+
'<section id="solution"><p class="section-kicker">THE APPLICATION</p><h2>How the solution works</h2><p>The Farmer Registry issues a Farmer Identity Credential and the Land Registry independently issues a Land Ownership Credential. Each authority retains its own records, issuer identity and signing boundary.</p><p>During a credit application, the wallet presents only selected claims from both credentials. The lender verifies the proper issuer for each role, holder control and matching Farmer IDs before using verified ownership, crop and cultivated acreage in a separate lending policy.</p>'+flow([['Farmer Registry','Farmer credential'],['Land Registry','Land credential'],['Wallet','Two credentials and consent'],['Lender','Verify, correlate and calculate']])+'</section>'+
lifecycle([['ISSUED BY FARMER REGISTRY','Farmer Identity Credential','{\n  "farmerId": "FMR-20481",\n  "registrationStatus": "ACTIVE"\n}','Stored as a separate holder-bound credential in the farmer’s wallet.'],['ISSUED BY LAND REGISTRY','Land Ownership Credential','{\n  "landId": "LAND-78432",\n  "farmerId": "FMR-20481",\n  "ownershipStatus": "ACTIVE",\n  "cultivatedAcres": 3.5,\n  "cropType": "WHEAT"\n}','Stored alongside the Farmer credential while retaining its independent issuer.']],'{\n  "farmerId": "FMR-20481",\n  "registrationStatus": "ACTIVE",\n  "ownershipStatus": "ACTIVE",\n  "cultivatedAcres": 3.5,\n  "cropType": "WHEAT"\n}', ['Farmer Registry and Land Registry are trusted for their respective roles.','Both signatures, algorithms and holder binding are valid.','Farmer ID matches across the two credentials.','Ownership is active and the crop is supported.','The lender calculates eligibility only after successful verification.'])+
video('Both issuance journeys, wallet persistence, bank QR request, minimum disclosure, loan calculation, ineligibility, mismatched-record rejection and refusal.')+
'<section id="experience"><p class="section-kicker">EXPERIENCE</p><h2>Journey demonstrated</h2>'+steps(['Authenticate and obtain the Farmer Identity Credential.','Authenticate and obtain the Land Ownership Credential.','Store both credentials in the same wallet.','Scan the bank request and review the requested facts.','Consent to a combined presentation.','Verify trust, holder and matching Farmer IDs.','Apply crop and acreage policy only after verification.'])+'<div class="decision"><span>DEMONSTRATION POLICY</span><strong>Active ownership + supported crop + matching Farmer ID</strong><p>Maximum loan = cultivated acres × approved crop rate</p></div></section>'+
'<section class="information"><h2>Information design</h2><div class="compare two"><div><span>Needed by the lender</span><strong>Farmer ID, registration, ownership, crop and cultivated acreage</strong></div><div><span>Kept private</span><strong>National ID, name, address, date of birth, Land ID and unrelated records</strong></div></div></section>'+
'<section id="adapt"><p class="section-kicker">REPLICATE THE PATTERN</p><h2>How to adapt it</h2>'+steps(['Identify farmer and land authorities.','Define separate registry schemas and stewardship.','Establish safe identity-to-farmer-to-land mappings.','Define credential claims and minimum lender disclosures.','Establish issuer onboarding, role trust and key governance.','Keep lending policy separate from verification.','Add governed rates, revocation, expiry, audit, privacy and security controls.'])+'</section>',

education: baseHeader('Learning and opportunity','Education credentials for admission and employment','Reuse trusted School, College and University credentials for different education and employment purposes.','REFERENCE IMPLEMENTATION')+
'<section id="problem"><p class="section-kicker">THE REAL-WORLD NEED</p><h2>The problem</h2><p>Education records accumulate across different institutions and years. Learners repeatedly assemble certificates and marks when applying for postgraduate study, employment, scholarships, professional registration or cross-border opportunities.</p><p>Universities and employers must determine whether every document is genuine, whether the institution is recognized, whether the records belong to one applicant and whether they satisfy a specific rule. Verification often relies on scans, portals, emails and phone calls.</p><p>The same history has different meanings for different purposes. A postgraduate programme may require higher thresholds than an employer’s first-round screen. The need is trusted, portable evidence that can be reused without merging institutional databases or sharing the learner’s complete record.</p></section>'+
'<section id="actors" class="ecosystem-scope"><p class="section-kicker">ECOSYSTEM</p><h2>Participants, reference coverage and integration boundaries</h2><p>The reference application makes three independently issued qualifications reusable for two decisions. This combined view shows institutional responsibilities, what is demonstrated or represented, and what remains outside the credential exchange.</p>'+ecosystemScope([['Learner','Obtains credentials and controls presentation across education and employment journeys.','demonstrated','Demonstrated','Synthetic learners authenticate, store credentials and present them for two purposes.','Real enrolment identity, corrections, recovery, accessibility and learner support.'],['School or awarding body','Maintains completion records and issues School credentials; for example, a school, examination board or ministry.','simulated','Represented and issued','A separate synthetic record, issuer identity and credential are implemented.','Connection to the institution’s student system, authorized issuance and correction process.'],['College or training provider','Maintains diploma, vocational or undergraduate records and issues credentials.','simulated','Represented and issued','A second independent record and issuer are implemented.','Institutional data integration, programme governance and production key custody.'],['University','Maintains degree records, issues credentials and may receive postgraduate applications.','simulated','Represented and issued','A third issuer and a separate admissions verifier are implemented.','Student-system integration, recognition checks, application management and admission-list process.'],['Recognition/accreditation body','Determines which institutions, programmes and qualifications are recognized; for example, a qualifications authority or accreditation agency.','outside','Not integrated','Configured issuer trust represents recognition for the demo.','Authoritative recognition registry, status changes, appeals and cross-border rules.'],['Wallet provider','Stores three credentials and discloses selected information by purpose.','demonstrated','Demonstrated','The same wallet and credentials serve both applications without reissuance.','Production assurance, recovery, device security and standards-profile acceptance.'],['Postgraduate institution','Verifies education history and evaluates admission-pool eligibility.','demonstrated','Demonstrated','The portal applies 60/60/70 and correctly stops at consideration for an admission list.','Application intake, ranking, quotas, fees, exceptions, final selection and enrolment.'],['Employer','Verifies qualifications and determines interview-round eligibility.','demonstrated','Demonstrated','A separate portal requests fewer marks and applies its 60% University rule.','Applicant tracking, skills and experience checks, interviews, background checks and employment.']])+'</section>'+
'<section id="solution"><p class="section-kicker">THE APPLICATION</p><h2>How the solution works</h2><p>School, College and University each maintain their own records and issue their own credential. The learner stores all three in one wallet. A common Learner ID supports correlation, while national and institution-specific identifiers remain on the issuer side.</p><p>The learner reuses the credentials with two verifiers. The Master’s institution and employer perform the same trust, holder and correlation checks but apply different purpose-specific policies.</p>'+flow([['School','School credential'],['College + University','Two further credentials'],['Learner wallet','Three reusable credentials'],['Two verifiers','Admission and interview rules']])+'</section>'+
lifecycle([['ISSUED BY SCHOOL','School Certificate','{\n  "learnerId": "LRN-31009",\n  "status": "PASSED",\n  "percentage": 72\n}','Stored independently in the learner wallet.'],['ISSUED BY COLLEGE','College Certificate','{\n  "learnerId": "LRN-31009",\n  "status": "PASSED",\n  "percentage": 68\n}','Stored independently in the same wallet.'],['ISSUED BY UNIVERSITY','University Degree','{\n  "learnerId": "LRN-31009",\n  "degree": "BSc Computer Science",\n  "status": "COMPLETED",\n  "percentage": 74\n}','Stored with its University issuer and holder binding intact.']],'{\n  "learnerId": "LRN-31009",\n  "school": { "status": "PASSED", "percentage": 72 },\n  "college": { "status": "PASSED", "percentage": 68 },\n  "university": {\n    "degree": "BSc Computer Science",\n    "status": "COMPLETED",\n    "percentage": 74\n  }\n}', ['Each institution is trusted for the credential role it performs.','All signatures, approved algorithms and holder bindings are valid.','Learner ID matches across all three credentials.','The verifier requests only claims needed for its stated purpose.','Admission or employment policy is applied after verification.'])+
video('All three credentials, the Master’s application, the employment application and distinct eligible, ineligible, rejection and refusal outcomes.','Education video · added after application acceptance')+
'<section id="experience"><p class="section-kicker">INTENDED EXPERIENCE</p><h2>Two purposes, the same trusted history</h2><h3>Master’s application</h3>'+steps(['Request all three education credentials.','Obtain learner consent.','Verify issuer roles, holder and Learner ID.','Apply School ≥60%, College ≥60% and relevant Bachelor degree ≥70%.','Accept an eligible application for consideration—not admission.'])+'<h3>Job application</h3>'+steps(['Request and verify the same three credentials.','Require completed School and College.','Require a relevant completed Bachelor degree with at least 60%.','Advance an eligible candidate to interview round one—not employment.'])+'</section>'+
'<section id="adapt"><p class="section-kicker">REPLICATE THE PATTERN</p><h2>How to adapt it</h2>'+steps(['Identify recognized institutions and awarding bodies.','Define learner and institution identifiers.','Model separate institutional schemas.','Define appropriate credentials and recognition governance.','Configure wallet discovery and minimum disclosure by purpose.','Keep admission and recruitment policies outside verification.','Add revocation, corrections, appeals, privacy and audit controls.'])+'</section>',

capabilities: baseHeader('Capability map','Sunbird RC capabilities across applications','The matrix describes what the reference applications demonstrate—not the limits of the domains or credential use cases Sunbird RC can support.')+
'<section><div class="table-wrap"><table><thead><tr><th>Capability</th><th>Age</th><th>Rural credit</th><th>Education</th></tr></thead><tbody>'+
[['Authoritative records','Citizen','Farmer and land','Learner and institutions'],['Credential issuers','One','Two','Three'],['Credentials together','One','Two','Three'],['Wallet-driven issuance','Yes','Yes','Yes'],['Selective disclosure','Age condition','Farmer, ownership, crop and acreage','Qualifications and results'],['Correlation','Not required','Farmer ID','Learner ID'],['Verifier services','Web and mobile age services','Farm-credit lender','Master’s and job applications'],['Decision','Age condition','Eligibility and maximum loan','Admission-pool and interview eligibility']].map(r=>'<tr>'+r.map((c,i)=>'<'+(i?'td':'th')+'>'+c+'</'+(i?'td':'th')+'>').join('')+'</tr>').join('')+'</tbody></table></div></section>'+
'<section id="solution"><p class="section-kicker">REUSABLE FOUNDATION</p><h2>What remains common</h2><p>Sunbird RC supports record modelling, issuer configuration, credentials derived from authoritative data and credential exchange. Ecosystems add governance, mappings, trust, disclosure policies and service rules.</p>'+flow([['Model','Entities and schemas'],['Issue','Trusted credentials'],['Exchange','Compatible wallets'],['Use','Services and decisions']])+'</section>'+
'<section id="adapt"><p class="section-kicker">CONFIGURE FOR CONTEXT</p><h2>What every implementation decides</h2>'+steps(['Authoritative organizations and stewardship.','Identifiers and permitted mappings.','Issuer identities, keys and trust governance.','Credential claims and minimum disclosure.','Wallet and protocol compatibility.','Verifier purpose and policy.','Production privacy, revocation, security and operations.'])+'</section>',

adapt: baseHeader('Guide','Adapt a Sunbird RC application pattern','A reusable structure for explaining and implementing another trusted-registry and credential application.')+
'<section id="problem"><p class="section-kicker">START WITH THE NEED</p><h2>Define the real-world problem</h2><p>Describe the affected people and organizations, why existing records or documents are difficult to use, and what improved service outcome is required. Do not begin with technology.</p></section>'+
'<section id="actors"><p class="section-kicker">MAP THE ECOSYSTEM</p><h2>Separate authoritative roles</h2><p>Identify record authorities, credential issuers, holders, wallets, verifiers and recognition bodies. Preserve real institutional boundaries rather than combining actors for diagram simplicity.</p></section>'+
'<section id="solution"><p class="section-kicker">DESIGN THE APPLICATION</p><h2>Connect registry, credential and service</h2>'+flow([['Authority','Maintain records'],['Issuer','Create credential'],['Holder','Control presentation'],['Verifier','Provide service']])+'</section>'+
'<section id="adapt"><p class="section-kicker">IMPLEMENT RESPONSIBLY</p><h2>Replication sequence</h2>'+steps(['Model authoritative records and identifiers.','Define credentials and minimum claims.','Establish issuer and verifier trust governance.','Select and test a standards-compatible wallet.','Separate verification from domain policy.','Design positive, negative and refusal outcomes.','Add production privacy, security, revocation and operations.'])+'</section>'
};

const params = new URLSearchParams(location.search);
const key = params.get('page') || 'age';
const documentNode = document.getElementById('document');
documentNode.innerHTML = docs[key] || docs.age;
document.querySelectorAll('[data-page]').forEach(a => { if (a.dataset.page === key) a.classList.add('active'); });
const title = documentNode.querySelector('h1');
if (title) document.title = title.textContent + ' | Sunbird RC';
